version: "3.8"

services:
  bot:
    image: telegram-gpt
    container_name: telegram-gpt-container
    build:
      context: ./
    deploy:
      resources:
        limits:
          memory: 250M
    restart: on-failure
